# Generated by Django 4.2.30 on 2026-04-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customrequest_statuses_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='gcash', max_length=50),
        ),
    ]
