# Generated by Django - manual fix for tracking_id

from django.db import migrations, models
import django.db.models.deletion
import secrets


def generate_tracking_ids(apps, schema_editor):
    """Generate unique tracking IDs for existing orders"""
    Order = apps.get_model('api', 'Order')
    for order in Order.objects.all():
        # Generate unique tracking ID
        while True:
            tracking_id = secrets.token_urlsafe(16)[:16].upper().replace('-', '').replace('_', '')
            # Ensure uniqueness
            if not Order.objects.filter(tracking_id=tracking_id).exists():
                order.tracking_id = tracking_id
                order.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_unique_together_cart_unique_cart_item'),
    ]

    operations = [
        # Create Category model
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        
        # Add category to Product
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category'),
        ),
        
        # Add tracking_id as nullable first
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=32, null=True, blank=True, editable=False),
        ),
        
        # Generate tracking IDs for existing orders
        migrations.RunPython(generate_tracking_ids, migrations.RunPython.noop),
        
        # Make tracking_id non-nullable and unique
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=32, unique=True, editable=False),
        ),
        
        # Add phone to Order
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        
        # Add updated_at to Order
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Create UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('profile_picture', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
    ]
